# Site settings
title: "Kaiqi Yang"
name: "Kaiqi Yang"
email: "kqyang@msu.edu"
description: "Website of Korbin."


baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

# Set timezone (America/Detroit corresponds to Michigan, USA)
timezone: America/Detroit

# Collections
collections:
  publications:
    output: true
  misc:
    output: true

